# Generated by Django 5.2.6 on 2025-09-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('age', models.PositiveIntegerField(verbose_name='Yaş')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='annotated/')),
                ('dyslexic_count', models.IntegerField(default=0)),
                ('normal_count', models.IntegerField(default=0)),
                ('dyslexic_percent', models.FloatField(default=0.0)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
